# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Location.destroy_all
Student.destroy_all
Instructor.destroy_all
Reservation.destroy_all
Room.destroy_all

chicago = Location.create(name: "Chicago")
peoria = Location.create(name: "Peoria")
rockford = Location.create(name: "Rockford")
elgin = Location.create(name: "Elgin")
naperville = Location.create(name: "Naperville")
joliet = Location.create(name: "Joliet")
schaumberg = Location.create(name: "Schaumberg")
evanston = Location.create(name: "Evanston")
bolingbrook = Location.create(name: "Bolingbrook")
skokie = Location.create(name: "Skokie")
downers_grove = Location.create(name: "Downers Grove")
glenview = Location.create(name: "Glenview")
northbrook = Location.create(name: "Northbrook")

cole = Instructor.create(name: "Cole", bio: "I love science!", experience: 3, subject: "Physics", location_id: chicago.id)
derick = Instructor.create(name: "Derick", bio: "I love coding!", experience: 6, subject: "Computer Science", location_id: chicago.id)
max = Instructor.create(name: "Max", bio: "I love history!", experience: 10, subject: "History", location_id: chicago.id)
dena = Instructor.create(name: "Dena", bio: "I love math!", experience: 5, subject: "Algebra", location_id: chicago.id)
finn = Instructor.create(name: "Finn", bio: "I love science!", experience: 1, subject: "Biology", location_id: chicago.id)
ben = Instructor.create(name: "Ben", bio: "I love Spanish!", experience: 2, subject: "Spanish", location_id: chicago.id)
jordan = Instructor.create(name: "Jordan", bio: "I love French!", experience: 4, subject: "French", location_id: chicago.id)
eddie = Instructor.create(name: "Eddie", bio: "I love math!", experience: 7, subject: "Geometry", location_id: chicago.id)
lucas = Instructor.create(name: "Lucas", bio: "I love math!", experience: 3, subject: "Trigonometry", location_id: chicago.id)
kim = Instructor.create(name: "Kim", bio: "I love math!", experience: 2, subject: "Algebra", location_id: chicago.id)
nicolas = Instructor.create(name: "Nicolas", bio: "I love science!", experience: 6, subject: "Chemistry", location_id: chicago.id)
pierre = Instructor.create(name: "Pierre", bio: "I love science!", experience: 8, subject: "Biology", location_id: chicago.id)
emile = Instructor.create(name: "Emile", bio: "I love Italian!", experience: 9, subject: "Italian", location_id: chicago.id)
billy = Instructor.create(name: "Billy", bio: "I love coding!", experience: 2, subject: "Computer Science", location_id: downers_grove.id)
emily = Instructor.create(name: "Emily", bio: "I love science!", experience: 1, subject: "Physics", location_id: skokie.id)
thomas = Instructor.create(name: "Thomas", bio: "I love math!", experience: 4, subject: "Geometry", location_id: bolingbrook.id)
ana = Instructor.create(name: "Ana", bio: "I love science!", experience: 8, subject: "Chemistry", location_id: evanston.id)
mohamed = Instructor.create(name: "Max", bio: "I love coding!", experience: 10, subject: "Computer Science", location_id: schaumberg.id)
pablo = Instructor.create(name: "Pablo", bio: "I love history!", experience: 1, subject: "History", location_id: joliet.id)
alyssa = Instructor.create(name: "Alyssa", bio: "I love language arts!", experience: 6, subject: "Language Arts", location_id: naperville.id)
sead = Instructor.create(name: "Sead", bio: "I love science!", experience: 4, subject: "Physics", location_id: elgin.id)
rob = Instructor.create(name: "Rob", bio: "I love math!", experience: 8, subject: "Algebra", location_id: rockford.id)
gabriel = Instructor.create(name: "Gabriel", bio: "I love coding!", experience: 10, subject: "Computer Science", location_id: peoria.id)
william = Instructor.create(name: "William", bio: "I love language arts!", experience: 10, subject: "Language Arts", location_id: peoria.id)
kieran = Instructor.create(name: "Kieran", bio: "I love history!", experience: 3, subject: "History", location_id: peoria.id)
hector = Instructor.create(name: "Hector", bio: "I love science!", experience: 4, subject: "Chemistry", location_id: rockford.id)
abby = Instructor.create(name: "Abby", bio: "I love math!", experience: 2, subject: "Trigonometry", location_id: rockford.id)
dan = Instructor.create(name: "Dan", bio: "I love Spanish!", experience: 5, subject: "Spanish", location_id: elgin.id)
kate = Instructor.create(name: "Kate", bio: "I love French!", experience: 6, subject: "French", location_id: elgin.id)
jim = Instructor.create(name: "Jim", bio: "I love history!", experience: 3, subject: "History", location_id: naperville.id)
jane = Instructor.create(name: "Jane", bio: "I love math!", experience: 3, subject: "Algebra", location_id: naperville.id)
matt = Instructor.create(name: "Matt", bio: "I love coding!", experience: 2, subject: "Computer Science", location_id: joliet.id)
ann = Instructor.create(name: "Ann", bio: "I love science!", experience: 2, subject: "Algebra", location_id: joliet.id)
alec = Instructor.create(name: "Alec", bio: "I love math!", experience: 1, subject: "Geometry", location_id: schaumberg.id)
alex = Instructor.create(name: "Alex", bio: "I love language arts!", experience: 6, subject: "Language Arts", location_id: schaumberg.id)
joe = Instructor.create(name: "Joe", bio: "I love history!", experience: 9, subject: "History", location_id: evanston.id)
jen = Instructor.create(name: "Jen", bio: "I love math!", experience: 10, subject: "Algebra", location_id: evanston.id)
carol = Instructor.create(name: "Carol", bio: "I love Italian!", experience: 4, subject: "Italian", location_id: bolingbrook.id)
david = Instructor.create(name: "David", bio: "I love coding!", experience: 5, subject: "Computer Science", location_id: bolingbrook.id)
nick = Instructor.create(name: "Nick", bio: "I love math!", experience: 3, subject: "Trigonometry", location_id: skokie.id)
rick = Instructor.create(name: "Rick", bio: "I love science!", experience: 6, subject: "Chemistry", location_id: skokie.id)
leah = Instructor.create(name: "Leah", bio: "I love science!", experience: 8, subject: "Biology", location_id: downers_grove.id)
beth = Instructor.create(name: "beth", bio: "I love coding!", experience: 2, subject: "Computer Science", location_id: downers_grove.id)
lisa = Instructor.create(name: "Lisa", bio: "I love math!", experience: 4, subject: "Algebra", location_id: glenview.id)
joel = Instructor.create(name: "Joel", bio: "I love Italian!", experience: 5, subject: "Italian", location_id: glenview.id)
jill = Instructor.create(name: "Jill", bio: "I love science!", experience: 3, subject: "Physics", location_id: northbrook.id)
mikel = Instructor.create(name: "Mikel", bio: "I love history!", experience: 6, subject: "History", location_id: northbrook.id)

first_room_chi = Room.create(number: 1, location_id: chicago.id)
second_room_chi = Room.create(number: 2, location_id: chicago.id)
third_room_chi = Room.create(number: 3, location_id: chicago.id)
fourth_room_chi = Room.create(number: 4, location_id: chicago.id)
first_room_grove = Room.create(number: 1, location_id: downers_grove.id)
second_room_grove = Room.create(number: 2, location_id: downers_grove.id)
first_room_skokie = Room.create(number: 1, location_id: skokie.id)
second_room_skokie = Room.create(number: 2, location_id: skokie.id)
first_room_bolingbrook = Room.create(number: 1, location_id: bolingbrook.id)
second_room_bolingbrook = Room.create(number: 2, location_id: bolingbrook.id)
first_room_evanston = Room.create(number: 1, location_id: evanston.id)
second_room_evanston = Room.create(number: 2, location_id: evanston.id)
first_room_schaumberg = Room.create(number: 1, location_id: schaumberg.id)
second_room_schaumberg = Room.create(number: 2, location_id: schaumberg.id)
first_room_joliet = Room.create(number: 1, location_id: joliet.id)
second_room_joliet = Room.create(number: 2, location_id: joliet.id)
first_room_naperville = Room.create(number: 1, location_id: naperville.id)
second_room_naperville = Room.create(number: 2, location_id: naperville.id)
first_room_elgin = Room.create(number: 1, location_id: elgin.id)
second_room_elgin = Room.create(number: 2, location_id: elgin.id)
first_room_rockford = Room.create(number: 1, location_id: rockford.id)
second_room_rockford = Room.create(number: 2, location_id: rockford.id)
first_room_peoria = Room.create(number: 1, location_id: peoria.id)
second_room_peoria = Room.create(number: 2, location_id: peoria.id)
first_room_glen = Room.create(number: 1, location_id: glenview.id)
second_room_glen = Room.create(number: 2, location_id: glenview.id)
first_room_north = Room.create(number: 1, location_id: northbrook.id)
second_room_north = Room.create(number: 2, location_id: northbrook.id)